//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "DashboardView.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string DashboardView::genText(const DrTemplateData& DashboardView_view_data)
{
	drogon::OStringStream DashboardView_tmp_stream;
	std::string layoutName{""};
	DashboardView_tmp_stream << "<!DOCTYPE html>\n";
	DashboardView_tmp_stream << "<html lang=\"ar\" dir=\"rtl\">\n";
	DashboardView_tmp_stream << "<head>\n";
	DashboardView_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	DashboardView_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	DashboardView_tmp_stream << "    <title>لوحة التحكم - ";
{
    auto & val=DashboardView_view_data["full_name_ar"];
    if(val.type()==typeid(const char *)){
        DashboardView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        DashboardView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	DashboardView_tmp_stream << "</title>\n";
	DashboardView_tmp_stream << "    <link rel=\"stylesheet\" href=\"/css/style.css\">\n";
	DashboardView_tmp_stream << "</head>\n";
	DashboardView_tmp_stream << "<body>\n";
	DashboardView_tmp_stream << "    <nav class=\"navbar\">\n";
	DashboardView_tmp_stream << "        <div class=\"navbar-container\">\n";
	DashboardView_tmp_stream << "            <div class=\"navbar-brand\">\n";
	DashboardView_tmp_stream << "                <h1>لوحة التحكم</h1>\n";
	DashboardView_tmp_stream << "            </div>\n";
	DashboardView_tmp_stream << "            <div class=\"navbar-user\">\n";
	DashboardView_tmp_stream << "                <span class=\"user-name\">مرحباً، ";
{
    auto & val=DashboardView_view_data["full_name_ar"];
    if(val.type()==typeid(const char *)){
        DashboardView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        DashboardView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	DashboardView_tmp_stream << "</span>\n";
	DashboardView_tmp_stream << "                <a href=\"/admin/logout\" class=\"logout-link\">تسجيل الخروج</a>\n";
	DashboardView_tmp_stream << "            </div>\n";
	DashboardView_tmp_stream << "        </div>\n";
	DashboardView_tmp_stream << "    </nav>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "    <div class=\"dashboard-container\">\n";
	DashboardView_tmp_stream << "        <aside class=\"sidebar\">\n";
	DashboardView_tmp_stream << "            <ul class=\"sidebar-menu\">\n";
	DashboardView_tmp_stream << "                <li class=\"menu-item active\">\n";
	DashboardView_tmp_stream << "                    <a href=\"/admin/dashboard\">\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-icon\">🏠</span>\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-text\">الرئيسية</span>\n";
	DashboardView_tmp_stream << "                    </a>\n";
	DashboardView_tmp_stream << "                </li>\n";
	DashboardView_tmp_stream << "                <li class=\"menu-item\">\n";
	DashboardView_tmp_stream << "                    <a href=\"#\">\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-icon\">👥</span>\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-text\">المستخدمون</span>\n";
	DashboardView_tmp_stream << "                    </a>\n";
	DashboardView_tmp_stream << "                </li>\n";
	DashboardView_tmp_stream << "                <li class=\"menu-item\">\n";
	DashboardView_tmp_stream << "                    <a href=\"#\">\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-icon\">📊</span>\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-text\">التقارير</span>\n";
	DashboardView_tmp_stream << "                    </a>\n";
	DashboardView_tmp_stream << "                </li>\n";
	DashboardView_tmp_stream << "                <li class=\"menu-item\">\n";
	DashboardView_tmp_stream << "                    <a href=\"#\">\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-icon\">⚙️</span>\n";
	DashboardView_tmp_stream << "                        <span class=\"menu-text\">الإعدادات</span>\n";
	DashboardView_tmp_stream << "                    </a>\n";
	DashboardView_tmp_stream << "                </li>\n";
	DashboardView_tmp_stream << "            </ul>\n";
	DashboardView_tmp_stream << "        </aside>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "        <main class=\"main-content\">\n";
	DashboardView_tmp_stream << "            <div class=\"page-header\">\n";
	DashboardView_tmp_stream << "                <h2>مرحباً بك في لوحة التحكم</h2>\n";
	DashboardView_tmp_stream << "                <p class=\"page-subtitle\">هنا يمكنك إدارة جميع جوانب النظام</p>\n";
	DashboardView_tmp_stream << "            </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "            <div class=\"stats-grid\">\n";
	DashboardView_tmp_stream << "                <div class=\"stat-card\">\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-icon\">👤</div>\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-details\">\n";
	DashboardView_tmp_stream << "                        <h3>المستخدم الحالي</h3>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-value\">";
{
    auto & val=DashboardView_view_data["username"];
    if(val.type()==typeid(const char *)){
        DashboardView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        DashboardView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	DashboardView_tmp_stream << "</p>\n";
	DashboardView_tmp_stream << "                    </div>\n";
	DashboardView_tmp_stream << "                </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "                <div class=\"stat-card\">\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-icon\">🕐</div>\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-details\">\n";
	DashboardView_tmp_stream << "                        <h3>الوقت الحالي</h3>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-value\">";
{
    auto & val=DashboardView_view_data["current_time"];
    if(val.type()==typeid(const char *)){
        DashboardView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        DashboardView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	DashboardView_tmp_stream << "</p>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-label\">توقيت عمّان</p>\n";
	DashboardView_tmp_stream << "                    </div>\n";
	DashboardView_tmp_stream << "                </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "                <div class=\"stat-card\">\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-icon\">📅</div>\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-details\">\n";
	DashboardView_tmp_stream << "                        <h3>التاريخ</h3>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-value\" id=\"current-date\"></p>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-label\">التقويم الميلادي</p>\n";
	DashboardView_tmp_stream << "                    </div>\n";
	DashboardView_tmp_stream << "                </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "                <div class=\"stat-card\">\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-icon\">✅</div>\n";
	DashboardView_tmp_stream << "                    <div class=\"stat-details\">\n";
	DashboardView_tmp_stream << "                        <h3>حالة النظام</h3>\n";
	DashboardView_tmp_stream << "                        <p class=\"stat-value status-active\">نشط</p>\n";
	DashboardView_tmp_stream << "                    </div>\n";
	DashboardView_tmp_stream << "                </div>\n";
	DashboardView_tmp_stream << "            </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "            <div class=\"content-section\">\n";
	DashboardView_tmp_stream << "                <h3>الإجراءات السريعة</h3>\n";
	DashboardView_tmp_stream << "                <div class=\"actions-grid\">\n";
	DashboardView_tmp_stream << "                    <button class=\"action-button\" disabled>\n";
	DashboardView_tmp_stream << "                        <span class=\"action-icon\">➕</span>\n";
	DashboardView_tmp_stream << "                        <span>إضافة مستخدم</span>\n";
	DashboardView_tmp_stream << "                    </button>\n";
	DashboardView_tmp_stream << "                    <button class=\"action-button\" disabled>\n";
	DashboardView_tmp_stream << "                        <span class=\"action-icon\">📝</span>\n";
	DashboardView_tmp_stream << "                        <span>عرض السجلات</span>\n";
	DashboardView_tmp_stream << "                    </button>\n";
	DashboardView_tmp_stream << "                    <button class=\"action-button\" disabled>\n";
	DashboardView_tmp_stream << "                        <span class=\"action-icon\">📈</span>\n";
	DashboardView_tmp_stream << "                        <span>إنشاء تقرير</span>\n";
	DashboardView_tmp_stream << "                    </button>\n";
	DashboardView_tmp_stream << "                    <button class=\"action-button\" disabled>\n";
	DashboardView_tmp_stream << "                        <span class=\"action-icon\">🔧</span>\n";
	DashboardView_tmp_stream << "                        <span>الإعدادات</span>\n";
	DashboardView_tmp_stream << "                    </button>\n";
	DashboardView_tmp_stream << "                </div>\n";
	DashboardView_tmp_stream << "            </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "            <div class=\"info-box\">\n";
	DashboardView_tmp_stream << "                <h4>معلومات النظام</h4>\n";
	DashboardView_tmp_stream << "                <ul>\n";
	DashboardView_tmp_stream << "                    <li>اللغة: العربية</li>\n";
	DashboardView_tmp_stream << "                    <li>الاتجاه: من اليمين إلى اليسار (RTL)</li>\n";
	DashboardView_tmp_stream << "                    <li>المنطقة الزمنية: آسيا/عمّان (UTC+3)</li>\n";
	DashboardView_tmp_stream << "                    <li>صيغة الأرقام: 0123456789</li>\n";
	DashboardView_tmp_stream << "                    <li>التقويم: الميلادي</li>\n";
	DashboardView_tmp_stream << "                </ul>\n";
	DashboardView_tmp_stream << "            </div>\n";
	DashboardView_tmp_stream << "        </main>\n";
	DashboardView_tmp_stream << "    </div>\n";
DashboardView_tmp_stream<<"\n";
	DashboardView_tmp_stream << "    <script src=\"/js/app.js\"></script>\n";
	DashboardView_tmp_stream << "</body>\n";
	DashboardView_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(DashboardView_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = DashboardView_view_data;
auto str = std::move(DashboardView_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
