//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class DashboardView:public drogon::DrTemplate<DashboardView>
{
public:
	DashboardView(){};
	virtual ~DashboardView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
