//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "LoginView.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string LoginView::genText(const DrTemplateData& LoginView_view_data)
{
	drogon::OStringStream LoginView_tmp_stream;
	std::string layoutName{""};
	LoginView_tmp_stream << "<!DOCTYPE html>\n";
	LoginView_tmp_stream << "<html lang=\"ar\" dir=\"rtl\">\n";
	LoginView_tmp_stream << "<head>\n";
	LoginView_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	LoginView_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	LoginView_tmp_stream << "    <title>تسجيل الدخول - لوحة الإدارة</title>\n";
	LoginView_tmp_stream << "    <link rel=\"stylesheet\" href=\"/css/style.css\">\n";
	LoginView_tmp_stream << "</head>\n";
	LoginView_tmp_stream << "<body>\n";
	LoginView_tmp_stream << "    <div class=\"login-container\">\n";
	LoginView_tmp_stream << "        <div class=\"login-box\">\n";
	LoginView_tmp_stream << "            <h1 class=\"login-title\">لوحة الإدارة</h1>\n";
	LoginView_tmp_stream << "            <h2 class=\"login-subtitle\">تسجيل الدخول</h2>\n";
LoginView_tmp_stream<<"\n";
	LoginView_tmp_stream << "            ";
 try {
                    std::string error = LoginView_view_data.get<std::string>("error");
                    if(!error.empty()) { 
	LoginView_tmp_stream << "            <div class=\"error-message\">\n";
	LoginView_tmp_stream << "                ";
                    if(error == "missing_credentials") { 
	LoginView_tmp_stream << "                    <p>الرجاء إدخال اسم المستخدم وكلمة المرور</p>\n";
	LoginView_tmp_stream << "                ";
 } else if(error == "invalid_credentials") { 
	LoginView_tmp_stream << "                    <p>اسم المستخدم أو كلمة المرور غير صحيحة</p>\n";
	LoginView_tmp_stream << "                ";
 } else if(error == "account_disabled") { 
	LoginView_tmp_stream << "                    <p>الحساب معطل. الرجاء التواصل مع المسؤول</p>\n";
	LoginView_tmp_stream << "                ";
 } else if(error == "account_locked") { 
	LoginView_tmp_stream << "                    <p>تم قفل الحساب بسبب محاولات دخول فاشلة متعددة</p>\n";
	LoginView_tmp_stream << "                ";
 } else if(error == "system_error") { 
	LoginView_tmp_stream << "                    <p>حدث خطأ في النظام. الرجاء المحاولة لاحقاً</p>\n";
	LoginView_tmp_stream << "                ";
 } 
	LoginView_tmp_stream << "            </div>\n";
	LoginView_tmp_stream << "            ";
 }} catch(...) {} 
LoginView_tmp_stream<<"\n";
	LoginView_tmp_stream << "            <form action=\"/admin/login\" method=\"POST\" class=\"login-form\">\n";
	LoginView_tmp_stream << "                <div class=\"form-group\">\n";
	LoginView_tmp_stream << "                    <label for=\"username\">اسم المستخدم</label>\n";
	LoginView_tmp_stream << "                    <input type=\"text\"\n";
	LoginView_tmp_stream << "                           id=\"username\"\n";
	LoginView_tmp_stream << "                           name=\"username\"\n";
	LoginView_tmp_stream << "                           class=\"form-input\"\n";
	LoginView_tmp_stream << "                           required\n";
	LoginView_tmp_stream << "                           autofocus\n";
	LoginView_tmp_stream << "                           autocomplete=\"username\"\n";
	LoginView_tmp_stream << "                           dir=\"ltr\">\n";
	LoginView_tmp_stream << "                </div>\n";
LoginView_tmp_stream<<"\n";
	LoginView_tmp_stream << "                <div class=\"form-group\">\n";
	LoginView_tmp_stream << "                    <label for=\"password\">كلمة المرور</label>\n";
	LoginView_tmp_stream << "                    <input type=\"password\"\n";
	LoginView_tmp_stream << "                           id=\"password\"\n";
	LoginView_tmp_stream << "                           name=\"password\"\n";
	LoginView_tmp_stream << "                           class=\"form-input\"\n";
	LoginView_tmp_stream << "                           required\n";
	LoginView_tmp_stream << "                           autocomplete=\"current-password\"\n";
	LoginView_tmp_stream << "                           dir=\"ltr\">\n";
	LoginView_tmp_stream << "                </div>\n";
LoginView_tmp_stream<<"\n";
	LoginView_tmp_stream << "                <button type=\"submit\" class=\"login-button\">دخول</button>\n";
	LoginView_tmp_stream << "            </form>\n";
LoginView_tmp_stream<<"\n";
	LoginView_tmp_stream << "            <div class=\"login-footer\">\n";
	LoginView_tmp_stream << "                <p class=\"time-display\">التوقيت: ";
{
    auto & val=LoginView_view_data["current_time"];
    if(val.type()==typeid(const char *)){
        LoginView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        LoginView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	LoginView_tmp_stream << " (عمّان)</p>\n";
	LoginView_tmp_stream << "            </div>\n";
	LoginView_tmp_stream << "        </div>\n";
	LoginView_tmp_stream << "    </div>\n";
	LoginView_tmp_stream << "</body>\n";
	LoginView_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(LoginView_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = LoginView_view_data;
auto str = std::move(LoginView_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
