//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class LoginView:public drogon::DrTemplate<LoginView>
{
public:
	LoginView(){};
	virtual ~LoginView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
